### ISSUE TITLE
Error:Task with name 'transformClassesWithMultidexlistForDebug' not found

### ISSUE THREAD

**Issue by hexi** [typ0520/fastdex#1]
我新创建一个项目的时候，加上fastdex插件，gradle同步的时候就会报这个错误

**Comment by typ0520** [comment]
已在0.0.2-rc2版本解决，如果multiDexEnabled = false，transformClassesWithMultidexlistForDebug这个任务就不存在

**Comment by hexi** [comment]
thanks
