### ISSUE TITLE
Error:Execution failed for task ':athit:transformClassesWithDexForDebug'.

### ISSUE THREAD

**Issue by gitwizChen** [typ0520/fastdex#10]
Error:Execution failed for task ':athit:transformClassesWithDexForDebug'.
> java.nio.file.NoSuchFileException: /Users/wizChen/MyAppRootPath/build/generated/source/greendao

**Comment by typ0520** [comment]
@gitwizChen 关掉自定义的编译任务，恢复成原来的

fastdex {
    useCustomCompile = false
}
