### ISSUE TITLE
亲测无软用

### ISSUE THREAD

**Issue by dndxxiangyu** [typ0520/fastdex#13]
从3m到2.5m，效果不是很明显。

**Comment by 1020112275** [comment]
@dndxxiangyu 如果你的系统是windows，下午会发一个新版本适配windows，请确保关闭掉instant run，另外第一次需要全量打包速度肯定慢，以后就会很快了，仔细看下readme；如果确保了以上这些都做了，还是那么慢，可以把全量打包和补丁打包的日志都贴出来

**Comment by typ0520** [comment]
@dndxxiangyu 建议你提issue时说详细点，如果你的系统是windows，下午会发一个新版本适配windows；另外请确保关闭掉instant run，另外第一次需要全量打包速度肯定慢，以后就会很快了，仔细看下readme；如果确保了以上这些都做了，还是那么慢，可以把全量打包和补丁打包的日志都贴出来

**Comment by justek-Wade** [comment]
@typ0520 请问windows的系统现在没效果吗

**Comment by typ0520** [comment]
@dndxxiangyu 已经发了0.0.3-beta6，之前在windows上跑会报错，现在解决了
