### ISSUE TITLE
com.dx168.fastdex.build.util.FileUtils#isLegalFile.

### ISSUE THREAD

**Issue by MagicMashRoom** [typ0520/fastdex#16]
Error:Execution failed for task ':uschool:transformClassesWithDexForHqyxAtestDebug'.
> Ambiguous method overloading for method com.dx168.fastdex.build.util.FileUtils#isLegalFile.
  Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
  	[class java.io.File]
  	[class java.lang.String]

**Comment by typ0520** [comment]
@MagicMashRoom   换0.0.3-beta6试下，已经解决了

**Comment by MagicMashRoom** [comment]
thanks
