### ISSUE TITLE
Dex: Error converting bytecode to dex: Cause: java.lang.NullPointerException

### ISSUE THREAD

**Issue by itcayman** [typ0520/fastdex#22]
![2017-03-31 6 59 37](https://cloud.githubusercontent.com/assets/5900963/24547830/5c160b4e-1644-11e7-9b81-eeeda3de3b62.png)
编译失败，项目中接入了Tinker

**Comment by typ0520** [comment]
@itcayman 建议你开发阶段关掉tinker可能会有潜在的问题，关掉tinker能提高打包速度，上线的时候把tinker打开通过脚本控制

**Comment by typ0520** [comment]
@itcayman 这个问题解决了，你之前出错时的android gradle build版本是2.3.0吧，换成2.3.1，fastdex的版本换成0.1.0就没问题了
