### ISSUE TITLE
Excution Failed for task app:transformClassesWithDexForDebug

### ISSUE THREAD

**Issue by ManBali** [typ0520/fastdex#24]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> ==fastdex jar input size is 76, expected is 1

我集成是代码如下：
project 下面的build.gradle
![image](https://cloud.githubusercontent.com/assets/5617446/24845298/7d7cdd48-1de3-11e7-9509-ba7f5b620064.png)

app下面的build.gradle是
![image](https://cloud.githubusercontent.com/assets/5617446/24845299/87c72132-1de3-11e7-836f-0a52edeab54f.png)

是不是还需要有其它的地方配置？或者是有可能是哪边的情况？

**Comment by typ0520** [comment]
@wsf5918 你是否开启了multidex，如果开启了multidex正常应该会走jarmerging，你的工程好像没走

**Comment by ManBali** [comment]
@typ0520 @typ0520 我的工程开启了Multidex，您的意思是需要关闭Multidex么？但是关闭后，会有这样的问题。如下：
Error:The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

**Comment by typ0520** [comment]
@wsf5918 不是关闭掉Multidex，正常情况下开启了multidex正常应该会走jarmerging，你的工程好像没走jarmerging或者merge失败，后面的任务发现jar没有合并就抛异常了，你按照这个[链接](https://github.com/typ0520/fastdex/issues/11)所说的issue格式把完整的信息提上来

**Comment by typ0520** [comment]
@wsf5918 已经在0.1.5版本解决
