### ISSUE TITLE
普通的编译可以，但是使用了fastdex就出现错误了，有没什么方式可以调试

### ISSUE THREAD

**Issue by zasdsd** [typ0520/fastdex#28]
16:49:33.952 [ERROR] [org.gradle.BuildExceptionReporter] 
16:49:33.953 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
16:49:33.954 [ERROR] [org.gradle.BuildExceptionReporter] 
16:49:33.954 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
16:49:33.954 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':taojinroad:fastdexCustomCompileTaojinroadDebugJavaWithJavac'.
16:49:33.954 [ERROR] [org.gradle.BuildExceptionReporter] > Invalid directory: /Users/zhengmj/Desktop/TjrTaojinRoad/taojinroad/build/generated/source/r/debug
16:49:33.955 [ERROR] [org.gradle.BuildExceptionReporter] 
16:49:33.955 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
16:49:33.955 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':taojinroad:fastdexCustomCompileTaojinroadDebugJavaWithJavac'.
16:49:33.955 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
16:49:33.955 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
16:49:33.955 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
16:49:33.955 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
16:49:33.955 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
16:49:33.955 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
16:49:33.955 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.IllegalArgumentException: Invalid directory: /Users/zhengmj/Desktop/TjrTaojinRoad/taojinroad/build/generated/source/r/debug
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.dx168.fastdex.build.snapshoot.file.BaseDirectorySnapshoot.<init>(BaseDirectorySnapshoot.java:50)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.dx168.fastdex.build.snapshoot.sourceset.JavaDirectorySnapshoot.<init>(JavaDirectorySnapshoot.java:33)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.dx168.fastdex.build.util.ProjectSnapshoot.handleGeneratedSource(ProjectSnapshoot.groovy:66)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.dx168.fastdex.build.util.ProjectSnapshoot.prepareEnv(ProjectSnapshoot.groovy:30)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.dx168.fastdex.build.util.ProjectSnapshoot$prepareEnv.call(Unknown Source)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.dx168.fastdex.build.variant.FastdexVariant.prepareEnv(FastdexVariant.groovy:125)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.dx168.fastdex.build.variant.FastdexVariant$prepareEnv.call(Unknown Source)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.dx168.fastdex.build.task.FastdexCustomJavacTask.compile(FastdexCustomJavacTask.groovy:41)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
16:49:33.956 [ERROR] [org.gradle.BuildExceptionReporter] 	... 14 more
16:49:33.957 [ERROR] [org.gradle.BuildExceptionReporter]

**Comment by typ0520** [comment]
@zasdsd 换成0.0.9这个版本试试，0.0.7有点问题

**Comment by typ0520** [comment]
0.0.9还是会有这个问题，关注下issue#27修复后会在这上面说

**Comment by typ0520** [comment]
@zasdsd 换这个版本0.1.0-beta
