### ISSUE TITLE
Execution failed for task ':app:transformClassesWithDexForDebug'. > Cannot cast object 'com.dx168.fastdex.build.transform.FastdexTransform@538e9fd6' with class 'com.dx168.fastdex.build.transform.FastdexTransform' to class 'com.android.build.gradle.internal.transforms.DexTransform'

### ISSUE THREAD

**Issue by Licardo** [typ0520/fastdex#34]
不懂这个问题怎么产生的：

app:compileDebugJavaWithJavac took 22107ms
taskName:compileDebugJavaWithJavac
outputs.files.files: ------------start----------------- 
/Users/zhanghao/AndroidStudioProjects/background-rest_phone/app/build/intermediates/classes/debug 
outputs.files.files: ---------------end------------------ 
:app:compileDebugSources
:app:compileDebugSources took 0ms
:app:mergeDebugAssets UP-TO-DATE
:app:mergeDebugAssets took 7ms
taskName:mergeDebugAssets
outputs.files.files: ------------start----------------- 
/Users/zhanghao/AndroidStudioProjects/background-rest_phone/app/build/intermediates/incremental/mergeDebugAssets 
/Users/zhanghao/AndroidStudioProjects/background-rest_phone/app/build/intermediates/assets/debug 
outputs.files.files: ---------------end------------------ 
:app:transformClassesWithDexForDebug
DexKnife Processing ...
:app:transformClassesWithDexForDebug FAILED
:app:transformClassesWithDexForDebug took 56ms
taskName:transformClassesWithDexForDebug
outputs.files.files: ------------start----------------- 
/Users/zhanghao/AndroidStudioProjects/background-rest_phone/app/build/intermediates/transforms/dex/debug 
outputs.files.files: ---------------end------------------ 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> Cannot cast object 'com.dx168.fastdex.build.transform.FastdexTransform@538e9fd6' with class 'com.dx168.fastdex.build.transform.FastdexTransform' to class 'com.android.build.gradle.internal.transforms.DexTransform'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 27.829 secs
Task timings:
     50ms  :share_core:mergeReleaseResources
     59ms  :share_service:mergeReleaseResources
     60ms  :share_navigation:mergeReleaseResources
     52ms  :rest.navigation:mergeReleaseResources
    152ms  :app:incrementalDebugJavaCompilationSafeguard
   1854ms  :rest.bo:compileReleaseJavaWithJavac
     52ms  :rest.common.update:mergeReleaseResources
     57ms  :rest.common.view:mergeReleaseResources
    208ms  :app:mergeDebugResources
     91ms  :app:dataBindingProcessLayoutsDebug
    317ms  :app:processDebugManifest
     60ms  :app:fastdexCustomCompileDebugJavaWithJavac
  22107ms  :app:compileDebugJavaWithJavac
     56ms  :app:transformClassesWithDexForDebug

**Comment by typ0520** [comment]
@Licardo 应该是别的gradle插件强转transform造成的，你都是依赖了那些插件最好贴到issue上

**Comment by typ0520** [comment]
fastdex和dexcount-gradle-plugin这个插件有冲突，建议去掉这个插件。可以使用下面这个jar包来计算dex的方法数

```
java -jar dex-method-counts.jar apk文件的路径
```

[dex-method-counts.jar.zip](https://github.com/typ0520/fastdex/files/1546424/dex-method-counts.jar.zip)
