### ISSUE TITLE
[0.2.0 版本功能规划]

### ISSUE THREAD

**Issue by typ0520** [typ0520/fastdex#37]
1、免安装(通过adb把补丁dex和资源推到手机) (done)
2、编写idea插件服务于免安装功能

**Comment by VeHan** [comment]
我也在尝试这方面的东西，能加入你一起完善这个工具吗

**Comment by typ0520** [comment]
可以啊，你想做哪方面呢。免安装已经实现了目前是全量推最好做成增量，另外idea插件、adt插件适配这些还没做。你可以先把目前代码熟悉一下

**Comment by VeHan** [comment]
idea插件可以考虑下，不知道adt插件有没有必要，重点idea吧，我觉得

**Comment by typ0520** [comment]
adt插件意义很大，动态代码生成会导致java代码增量编译不可用

**Comment by VeHan** [comment]
你说的adt不知道是否是android develop toolkit，我不太明白这跟免安装有什么关系

**Comment by typ0520** [comment]
这两个没有关系的，指的是用来做生成java代码的gradle插件(比如butterknife、Dagger2它们的gradle插件)

**Comment by VeHan** [comment]
那个是apt工具吧，annotation process tool

**Comment by typ0520** [comment]
@VeHan  我确认了下这个名词确实叫apt，是我搞错了，感谢指正  ^_^

**Comment by VeHan** [comment]
@typ0520 没关系，现在做到什么程度了

**Comment by typ0520** [comment]
还没做呢 V_V

**Comment by typ0520** [comment]
@VeHan 已经适配的差不多了正在测试，代码在apt分支

**Comment by typ0520** [comment]
功能已完成  0.3-rc1

**Comment by VeHan** [comment]
厉害了
