### ISSUE TITLE
感觉效果不明显？

### ISSUE THREAD

**Issue by hippyk** [typ0520/fastdex#39]
作者做过对比测试吗？结果如何？

**Comment by typ0520** [comment]
第一次全量打包要做注入会很慢，第一次补丁打包需要生成public.xml ids.xml会慢些，第二次补丁打包以后就快很多，另外如果你的library工程特别多，最多打成aar放到maven去依赖，这样就不用每次补丁打包都去做提取

**Comment by typ0520** [comment]
我们的工程正常打包时间是两分钟，第二次补丁打包一般在10秒至20秒之间

**Comment by typ0520** [comment]
可以尝试通过./gradlew fastdexDebug去打包，如果已经运行了这个apk会直接通过adb把补丁推到app里，不用安装了

**Comment by hippyk** [comment]
我仔细做了对比测试，没发现任何速度提升，而且还经常出错，建议大家慎用。

**Comment by typ0520** [comment]
@hippyk 如果觉得效果不是很明显可以提供下打包日志，这样维护者可以根据日志找原因，也许是一个bug，也许是配置的不对；另外你说经常出错，不把错误堆栈信息贴上来维护者怎么找原因？   不知道你发这条信息的意思何在，对你自己没有任何好处，对这个开源项目质量上的提升也没有任何的帮助，还影响维护者的心情；开源不是义务，而是兴趣，所以才花费大量工作以外的时间去开发新功能、解决issue ，之前在知乎上看过一篇文章，现在看来还是很有道理的。。。。。。 https://zhuanlan.zhihu.com/p/25768464

**Comment by hippyk** [comment]
我是觉得自己白白浪费了时间，所以提醒一下大家。同时也提醒维护者重新考虑此项目的价值。并没有恶意，不要误会。最后还是要感谢为此项目做出贡献的所有人。

**Comment by lichen228** [comment]
@hippyk “我仔细做了对比测试，没发现任何速度提升”。既然仔细对比过，对比的方式和耗时数据麻烦发下

**Comment by hippyk** [comment]
我就是简单的以自己目前的项目进行的测试，随意修改一个文件，build，一般大概在5、6s左右，加不加fastdex都差不多，即使打开优化butterknife选项也一样，而且加了fd偶尔会出错，需要clean。也许本来时间就不长，所以优化空间小？

**Comment by typ0520** [comment]
fastdex主要是对dex生成的过程做优化，你的项目编译在5、6s左右，生成dex的过程估计一秒都用不到，即使有效果也感觉不到啊，编译已经很快了也没必要用加速组件了；butterknife优化属于adt插件适配的工作，这块还没来得及做

**Comment by hippyk** [comment]
不过我之前用虚拟机时间比较长的时候，虽然没有精确测试，但是感觉似乎也不明显
