### ISSUE TITLE
:fastdexCustomCompileMohoTeacherDebugJavaWithJavac

### ISSUE THREAD

**Issue by appdev** [typ0520/fastdex#4]
```java
Error:Execution failed for task ':app-t:fastdexCustomCompileMohoTeacherDebugJavaWithJavac'.
> Compile failed; see the compiler error output for details.
```

**Comment by typ0520** [comment]
@huclengyue 能给下具体的堆栈信息吗，从这些信息里看不出来那里出问题了

**Comment by appdev** [comment]
源代码
![yy 20170319144602](https://cloud.githubusercontent.com/assets/9107717/24078817/26b51b4c-0cb3-11e7-8c82-54f4f700be29.png)
直接写文本在代码中
![tim 20170319144547](https://cloud.githubusercontent.com/assets/9107717/24078812/1be39dce-0cb3-11e7-8657-a22f59aee4f9.png)
使用string资源
![yy 20170319144514](https://cloud.githubusercontent.com/assets/9107717/24078814/1d32a850-0cb3-11e7-93a7-20dbf5c1c00e.png)


所有的代码都是UTF-8

不改代码claen后在运行正常。然后不论运行多少次，对代码的修改都不会生效

**Comment by typ0520** [comment]
@huclengyue 换成这个版本0.0.3-beta1，加上这个配置暂时关掉自定义的编译任务
fastdex {
    useCustomCompile = false
}

**Comment by typ0520** [comment]
@huclengyue 找到问题了，在编译的时候，如果没有用-encoding参数指定JAVA源代码的编码格式，则javac会获得操作系统默认采用的编码格式；你的源文件是utf8的，自定义的编译任务编译时没有指定encoding，你是windows环境所以默认用了GBK；我改了下代码应该可以解决你这个问题，0.0.3-beta2，我没有windows环境测不了，你试试吧

**Comment by appdev** [comment]
又有新的错误：
![yy 20170321143840](https://cloud.githubusercontent.com/assets/9107717/24136350/54cc20d8-0e49-11e7-81b4-caa067deff76.png)
![yy 20170321143909](https://cloud.githubusercontent.com/assets/9107717/24136349/54138898-0e49-11e7-8cd7-74f62f32ee1b.png)

**Comment by 1020112275** [comment]
@huclengyue 你指定的是1.8，我默认指定的是1.7，明天我在处理以下，使用gradle中配置的试试看

**Comment by typ0520** [comment]
@huclengyue 你使用了lambda表达式，及时这一步通过后，后面生成dex也会挂，需要走默认的compileJavaWithJavac任务经过retrolambda的处理才行，暂时无解，需要扒retrolambda的代码加上它的处理才行；建议你先别用lambda，看下Jake Wharton这篇文章https://realm.io/cn/news/360andev-jake-wharton-java-hidden-costs-android/

**Comment by appdev** [comment]
@typ0520 好的谢谢了。看来目前这个项目是不能用了，项目写的比较久了。里面用了很多lambda表达式。下个项目在用吧 还是谢谢了。

**Comment by typ0520** [comment]
@huclengyue 加上这个配置暂时关掉自定义的编译任务应该还是可以用的，只不过还是继续走默认的编译任务速度稍微慢了点而已
fastdex {
useCustomCompile = false
}
