### ISSUE TITLE
请问还有继续优化的空间吗？

### ISSUE THREAD

**Issue by ycdm** [typ0520/fastdex#40]
Task spend time:
     62ms  :app:mergePREDebugResources
     56ms  :app:dataBindingExportBuildInfoPREDebug
     94ms  :app:fastdexPrepareForPREDebug
   4178ms  :app:incrementalPREDebugJavaCompilationSafeguard
  16353ms  :app:compilePREDebugJavaWithJavac
    172ms  :app:transformClassesWithJarMergingForPREDebug
     96ms  :app:fastdexCreatePREDebugMaindexlistFileTask
    991ms  :app:transformClassesWithDexForPREDebug
    835ms  :app:packagePREDebug

Total time: 25.105 secs

一般是30多秒

**Comment by typ0520** [comment]
@ycdm 16353ms :app:compilePREDebugJavaWithJavac  这个任务还有很大的优化空间，adt插件的适配还没做，最近比较忙
