### ISSUE TITLE
databinding 修改XML ID，出现NoSuchFieldError

### ISSUE THREAD

**Issue by cenjunlei** [typ0520/fastdex#41]
java.lang.NoSuchFieldError: com.j.RulesBinding.tvClose 
我看了intermediates下的databinding目录下对应的类有这个全局变量，赋值正常

**Comment by ycdm** [comment]
感觉涉及到databinding的修改似乎比较容易出问题

**Comment by cenjunlei** [comment]
上面没设置useCustomCompile时可编译成功，以下设置了useCustomCompile = true，出现的错误，不能编译成功
fastdex {
        useCustomCompile = true
    }
10:45:23.273 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:javac] /Users/cenjunlei/Documents/app/build/fastdex/BaseDebug/work/custom-combind/com/j/RulesDialog.java:35: 错误: 找不到符号
10:45:23.273 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:javac]         mBinding.tvClose1.setOnClickListener(new View.OnClickListener() {
10:45:23.273 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:javac]                 ^
10:45:23.273 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:javac]   符号:   变量 tvClose1
10:45:23.273 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:javac]   位置: 类型为T的变量 mBinding
10:45:23.273 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:javac]   其中, T是类型变量:
10:45:23.273 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:javac]     T扩展已在类 BaseDataBingDialog中声明的ViewDataBinding
10:45:23.274 [WARN] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:javac] 1 个错误

**Comment by typ0520** [comment]
@cenjunlei 暂时先别开启useCustomCompile

**Comment by cenjunlei** [comment]
没开启时，databinding 修改XML ID，点击事件出现NoSuchFieldError 。freeline对databinding兼容性也不好 。不过你这个库除了细微修改不起作用和不支持databinding外，其他不错，我的macbookpro温度直接从99度变成70度上下

**Comment by typ0520** [comment]
@cenjunlei @ycdm 0.5.0-beta支持了dataBinding，如果开启了dataBinding，android gradle的版本最低支持2.0.0

```
classpath 'com.github.typ0520:fastdex-gradle:0.5.0-beta'
```
