### ISSUE TITLE
重命名后运行失败

### ISSUE THREAD

**Issue by wangqiankun** [typ0520/fastdex#42]
系统：macOS
gradle 版本：2.3.2

重现步骤：初次运行后，shift+f6 重命名 xml 文件名，再次运行提示找不到对应id（该id是老资源文件名）

**Comment by wangqiankun** [comment]
系统：macOS
gradle 版本：2.3.2

重现步骤：初次运行后，更改 shift+f6 重命名 xml 文件名，再次运行提示找不到对应id（该id是老资源文件名）

**Comment by typ0520** [comment]
碰到资源的问题把public.xml和ids.xml删除掉就好了
