### ISSUE TITLE
第一次编译后报错了～

### ISSUE THREAD

**Issue by sameland** [typ0520/fastdex#46]
> Failed to notify project evaluation listener.
   > com.android.utils.FileUtils.deleteFolder(Ljava/io/File;)V

上面的问题解决了 又出现了下面的问题：
Could not get unknown property 'manifestOutputFile' for task 'processDebugManifest' of type com.android.build.gradle.tasks.MergeManifests

**Comment by sameland** [comment]
找到问题了  对gradle 3.0以上有兼容性问题

需要这样改下
// Android Gradle Plugin >= 3.0.0
                   manifestPath = new File(variantOutput.processManifest.manifestOutputDirectory, "AndroidManifest.xml")

**Comment by typ0520** [comment]
@sameland Android Gradle Plugin >= 3.0.0 目前还不是正式版，还没有去做适配

**Comment by typ0520** [comment]
@sameland 换成0.8.4
