### ISSUE TITLE
Fragment在xml布局中添加EditText的imeActionId属性，仅第一次编译能正常运行

### ISSUE THREAD

**Issue by orannge** [typ0520/fastdex#52]
com.android.tools.build:gradle:2.3.1
gradle-3.3

Android Studio 2.x系列都能稳定复现，简单贴下log：

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.myapplication/com.test.myapplication.MyFragmentActivity}: android.view.InflateException: Binary XML file line #19: Binary XML file line #19: Error inflating class android.widget.EditText`

猜测出现此错误的原因是FragmentActivity或者Fragment的布局文件中使用了额外的id属性，例如EditText的imeActionId：

```
<EditText
    android:id="@+id/et"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:imeActionId="@+id/go"/>
```

fastdex下，Clean Project第一次编译时能正常运行，再次编译，加载该xml布局时会出错。其他控件有类似属性（或自定义属性）的情况暂未测试。

**Comment by typ0520** [comment]
能给下完整的打包日志吗，包含有堆栈信息的

**Comment by typ0520** [comment]
不用给日志了 重现了

**Comment by typ0520** [comment]
@orannge freeline上有一个同样的issue，上面给出了出问题的原因以及解决方案  https://github.com/alibaba/freeline/issues/291
另外在比较简单的工程里测试fastdex，是看不到效果的，代码多了才能看出效果 ^_^

**Comment by orannge** [comment]
Instant Run是支持`android:imeActionId="@+id/go"`这种的，为什么不能添加支持，难道每次遇到都要手动修改id吗？另外使用效果确实不明显，我整个工程编译大概2、3分钟左右，每次fastdexDebug增量都要40多秒，最后一个步骤就占了40秒，感觉比默认的还要久。

**Comment by typ0520** [comment]
那个actionId单独的定义出来弄一次就好了； 可以贴上来一份完整的日志，日志里有各个任务的时间，第一次全量编译要走安装的这个时间也是算在任务里，以后在改代码就直接通过adb把补丁dex和资源推到app里然后直接重启app，这样会很快
