### ISSUE TITLE
已经启动模拟器了，却提示没有发现设备

### ISSUE THREAD

**Issue by ysnows** [typ0520/fastdex#53]
* What went wrong:
Execution failed for task ':app:fastdexPatchForDebug'.
> 没有发现Android设备，请确认连接是否正常 adb devices

**Comment by typ0520** [comment]
执行下adb devices是否有显示设备呢

**Comment by ysnows** [comment]
显示设备，不用fastdex都是可以的

**Comment by ysnows** [comment]
![image](https://user-images.githubusercontent.com/11255869/30319831-84b31d32-97e3-11e7-9418-856307b7c5e9.png)


![image](https://user-images.githubusercontent.com/11255869/30319789-639390f0-97e3-11e7-9cec-2dca09acfd1e.png)

**Comment by typ0520** [comment]
你用的是那个版本的fastdex，试试0.4.1； 只有执行fastdexXXX任务才会使用adb，正常的走assemble是用不到的所以正常

**Comment by ysnows** [comment]
是0.4.1，用的fastdex插件的那个按钮

**Comment by ysnows** [comment]
用命令行也是这个问题

**Comment by typ0520** [comment]
这个就奇怪了，fastdex连接adb使用的是这段代码，可以把代码下载到机器上跑下，看下是否出现了异常
，注意里面的adb路径需要改下
https://github.com/typ0520/fastdex-test-project/blob/master/adbconnect

```
import com.android.ddmlib.AndroidDebugBridge;
import com.android.ddmlib.IDevice;

public class Main {
    public static void main(String[] args) {
        IDevice device;
        AndroidDebugBridge.init(false);
        AndroidDebugBridge bridge = AndroidDebugBridge.createBridge(
                "/Users/tong/Applications/android-sdk-macosx/platform-tools/adb", false);
        waitForDevice(bridge);
        IDevice devices[] = bridge.getDevices();
        //device = devices[0];

        System.out.println(devices.length);

        for (IDevice d : devices) {
            System.out.println(d);
        }
    }

    private static void waitForDevice(AndroidDebugBridge bridge) {
        int count = 0;
        while (!bridge.hasInitialDeviceList()) {
            try {
                Thread.sleep(100);
                count++;
            } catch (InterruptedException ignored) {
            }
            if (count > 300) {
                System.err.print("Time out");
                break;
            }
        }
    }
}
```

**Comment by ysnows** [comment]
![image](https://user-images.githubusercontent.com/11255869/30408918-7271637a-9934-11e7-8cb0-2fa9dc05b5ed.png)
能获得^~^

**Comment by typ0520** [comment]
这个问题在你的环境上能稳定重现吗，还是偶尔出现呢。帮把可以把下面这些信息贴出来，我配置上试试看

- com.android.tools.build:gradle版本号
- gradle版本号
- buildToolsVersion 版本号

如果感兴趣也可以自己看下，把代码拉下来，获取设备列表的代码在

https://github.com/typ0520/fastdex/blob/master/fastdex-gradle/src/main/groovy/fastdex/build/util/FastdexInstantRun.groovy

的preparedDevice方法里

![tree](https://user-images.githubusercontent.com/4417749/30409527-36ce4ff0-9938-11e7-8ed5-ecefcf4bc384.png)

如果要改代码调试，可以在你的工程里的build.gradle，配置下mavenLocal()

```
buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
}
```

改了fastdex里的代码后在，工程根目录下执行下面的代码就可以了

```
./gradlew install
```

**Comment by typ0520** [comment]
fixed with 0.5.2
