### ISSUE TITLE
跟install run的对比

### ISSUE THREAD

**Issue by xulong20130712** [typ0520/fastdex#57]
求教大神，fastdex跟install run区别体现在什么地方。不太了解，

**Comment by typ0520** [comment]
instant run和fastdex最主要的区别是热修复的原理不同，前者是在全量打包时转换class内容，拿这个方法为例

```
void hello {
     print("hello")
}
```

转换后的代码类似于这样

```
void  hello(){
    if (hasPatch()) {
         hello$xxx();
         return;
    }
}
```

这样的做法好处是如果修改了方法内的逻辑，不用重启app就可以实时生效；劣势是转换的逻辑较复杂，在一个中大型项目上全量打包会非常慢
。

fastdex热修复是以类为颗粒的，拿补丁class生成补丁dex插桩时放在被修复的类所在dex的前面，由于要解决检验的问题所以全量打包时也会往class中注入一段代码不过这个逻辑很简单速度还是比较快的，这个方案的好处是简单不容易出错，但是如果修改了代码必须要重启app，另外这个方案还有一个问题是在art下如果修改抽象类会出错，目前fastdex对这个问题的处理是如果检测这个错误就触发一次安装就好了，后面会尝试从根上解决这个问题

另外instant run是不支持5.0以下的设备，fastdex没有这个限制；
对于资源变化两个方案都是采用全量推送resources.ap_  如果资源比较多tcp传输还是很耗费时间的，这个问题fastdex正在处理不出意外0.7版本会有这个特性

其它的细节就不一一对比了，总而言之instant run适合小型的项目，fastdex适合中型项目，如果感兴趣建议把两套方案的代码都阅读一遍
