### ISSUE TITLE
jdk 1.8 编译失败

### ISSUE THREAD

**Issue by tianshaokai** [typ0520/fastdex#58]
![image](https://user-images.githubusercontent.com/6706496/30905567-c5a40336-a3a7-11e7-9637-ab98d5c68d7d.png)

**Comment by tianshaokai** [comment]
我使用的是 0.5.1 版本

**Comment by typ0520** [comment]
贴下完整的打包日志

**Comment by tianshaokai** [comment]
我现在又改成了0.1.6 版本了，等我再切换版本试试，

**Comment by tianshaokai** [comment]
这个问题最近没有遇到

**Comment by typ0520** [comment]
我这边重现了这个问题，在0.6.4上修复了
