### ISSUE TITLE
是不是gradle版本的问题

### ISSUE THREAD

**Issue by LambdaV5** [typ0520/fastdex#59]
[last-build-error-report.txt](https://github.com/typ0520/fastdex/files/1342935/last-build-error-report.txt)

**Comment by typ0520** [comment]
你用的是4.2啊，2.3.3建议用3.3，你先改成3.3我加个容错

**Comment by LambdaV5** [comment]
好的

**Comment by typ0520** [comment]
0.6.2解决了这个问题
