### ISSUE TITLE
class name (*) does not match path (*)

### ISSUE THREAD

**Issue by YuJunKui1995** [typ0520/fastdex#6]
Error:Error converting bytecode to dex:
Cause: PARSE ERROR:
class name (com/baidu/platform/comapi/map/n) does not match path (com/baidu/platform/comapi/map/N.class)
...while parsing com/baidu/platform/comapi/map/N.class

**Comment by typ0520** [comment]
@YuJunKui1995 这个是不是你的地图sdk比较旧，网上能搜到同类的错误，http://bbs.lbsyun.baidu.com/forum.php?mod=viewthread&tid=11746

**Comment by typ0520** [comment]
@YuJunKui1995 发下你使用的百度sdk的jar包，还有你当前的系统、com.android.tools.build:gradle版本号、studio的版本号都贴一下吧，我的邮箱php12345@163.com

**Comment by typ0520** [comment]
@YuJunKui1995 问题已解决，使用0.0.3-beta4这个版本，是因为mac和windows上文件不区分大小写，混淆后的包同一个路径下出现A.class和a.class，这个时候在mac和windows上解压jar包到硬盘上然后在压缩回去就会出问题，把这块的操作全部放在内存完成就可以解决了
