### ISSUE TITLE
Execution failed for task ':app-k12:packageDebug'

### ISSUE THREAD

**Issue by yushiwo** [typ0520/fastdex#60]
* What went wrong:
Execution failed for task ':app-k12:packageDebug'.
> /Users/xxx/GitProj/company/study-project/app/build/fastdex/Debug/fastdex-meta-info.json (No such file or directory)

**Comment by typ0520** [comment]
/Users/xxx/GitProj/company/study-project/app/build/fastdex/Debug/这个目录下有这个文件吗

**Comment by yushiwo** [comment]
描述下我使用的现象：
1、首次使用，编译是没有问题的
2、代码更新之后，编译就出现上面的问题了

然后现在我关闭fastdex插件，重新clean一遍，再开启插件，可以正常编译了

**Comment by typ0520** [comment]
你的android plugin版本用的是什么版本，2.3以下吗

**Comment by yushiwo** [comment]
2.3.2的

**Comment by typ0520** [comment]
这个问题应该是加入fastdex第一次编译时出现的，第一次加插件最好clean一下

**Comment by typ0520** [comment]
@yushiwo 0.7.2 解决了这个问题
