### ISSUE TITLE
No signature of method

### ISSUE THREAD

**Issue by kaleai** [typ0520/fastdex#62]
Error:No signature of method: static fastdex.build.util.GradleUtils.getAndroidGradlePluginVersion() is applicable for argument types: () values: []

In:
Android Studio 3.0 beta7
com.android.tools.build:gradle:3.0.0-beta7
Gradle 4.1

**Comment by typ0520** [comment]
android  gradle3.0目前还是beta版本，还没有适配

**Comment by typ0520** [comment]
能给下错误的堆栈信息吗

**Comment by kaleai** [comment]
![image](https://user-images.githubusercontent.com/9552155/31328942-35befd5e-ad0a-11e7-9096-54f5be1beef0.png)


15:54	Plugin Error: Fastdex Plugin threw an uncaught AssertionError. Disable Plugin

具体没找到定位的地方

**Comment by typ0520** [comment]
你这个是studio3.0，还没做测试，建议用稳定版

**Comment by kaleai** [comment]
没事，我就是测试一下。
