### ISSUE TITLE
window AS 3.0 gradle4.1 使用插件方式 点击小火箭提示Error: It's not an Android Gradle project currently?

### ISSUE THREAD

**Issue by zhx00100** [typ0520/fastdex#68]

**Comment by typ0520** [comment]
你这不是在android工程上点的吧

**Comment by zhx00100** [comment]
![image](https://user-images.githubusercontent.com/3771820/32870546-67feccde-cab7-11e7-91e4-70738eee40c3.png)

确实是android工程. 点绿色小箭头是可以允许的, 小火箭就弹error框

**Comment by typ0520** [comment]
检测是否是android工程是检查root project的build.gradle是否加了classpath 'com.android.tools.build:gradle:'，另外检测子项目中是否有加apply plugin: 'com.android.application'，你在检查一下； 也可以直接调用命令来跑 

```
gradlew.bat  fastdexNormalDebug
```

**Comment by typ0520** [comment]
如果确认是android项目同步下gradle，再不行就删掉.idea目录重新导入项目
