### ISSUE TITLE
app:fastdexCleanAll

### ISSUE THREAD

**Issue by QingMings** [typ0520/fastdex#7]
Error:Execution failed for task ':app:fastdexCleanAll'.
> No signature of method: static com.dx168.fastdex.build.util.FastdexUtils.cleanAllCache() is applicable for argument types: () values: []
  Possible solutions: cleanAllCache(org.gradle.api.Project, java.lang.String), cleanCache(org.gradle.api.Project, java.lang.String)

**Comment by typ0520** [comment]
@QingMings 已经修复了，犯了一个低级错误，换成这个版本0.0.3-beta1

**Comment by QingMings** [comment]
👌
