### ISSUE TITLE
 Could not resolve all dependencies for configuration ':app:apt'

### ISSUE THREAD

**Issue by checkming** [typ0520/fastdex#70]
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > Could not resolve all dependencies for configuration ':app:_debugApk'.
      > A problem occurred configuring project ':sliding_menu'.
         > Could not resolve all dependencies for configuration ':sliding_menu:classpath'.
            > Could not find com.android.tools.build:gradle:2.3.3.
              Searched in the following locations:
                  https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
                  https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.jar
              Required by:
                  project :sliding_menu
   > Could not resolve all dependencies for configuration ':app:apt'.
      > Project :app declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :sliding_menu.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

请问这是什么原因?

**Comment by typ0520** [comment]
这个包com.android.tools.build:gradle:2.3.3拉不到，有加jcenter()吗

```
repositories {
        jcenter()
    }
```
