### ISSUE TITLE
asset目录下的文件 再增量更新的时候 没有带

### ISSUE THREAD

**Issue by xiang473535976** [typ0520/fastdex#75]
![image](https://user-images.githubusercontent.com/18111614/33362249-7a37c806-d516-11e7-9824-6b0ded77f3eb.png)

这是一个html文件     全量安装的时候     能够带过去    增量更新的时候 就带不过去   请看看怎么回事哈  谢谢了 很不错的工具！！！！

**Comment by typ0520** [comment]
我刚看了一下这块有bug，打资源补丁的时候只打了assets目录下的，二级目录里的内容都没加进去

**Comment by typ0520** [comment]
@xiang473535976 换成0.8.4
