### ISSUE TITLE
can not cast DexTransform

### ISSUE THREAD

**Issue by sunshinehu** [typ0520/fastdex#79]
Cannot cast object 'fastdex.build.transform.FastdexDexTransform@38153b72' with class 'fastdex.build.transform.FastdexDexTransform' to class 'com.android.build.gradle.internal.transforms.DexTransform'

**Comment by typ0520** [comment]
你是不是加了dexcount-gradle-plugin这个插件，和这个有冲突，建议去掉这个插件。可以使用下面这个jar包来计算dex的方法数

```
java -jar dex-method-counts.jar apk文件的路径
```

[dex-method-counts.jar.zip](https://github.com/typ0520/fastdex/files/1546424/dex-method-counts.jar.zip)

**Comment by sunshinehu** [comment]
应该是和dexknife 这个插件有冲突，谢谢啦

**Comment by Yellow5A5** [comment]
请问这个冲突你这边如何兼容？我这边忽略处理依然会报错 @sunshinehu
