### ISSUE TITLE
FileNotFoundException : FastdexApplication

### ISSUE THREAD

**Issue by dongzy** [typ0520/fastdex#8]
Error:Execution failed for task ':app:tinkerSupportProcess_360DebugManifest'.
> java.io.FileNotFoundException: E:\newkp\kuaipiandroid\NewKp\app\src\main\java\com\dx168\fastdex\runtime\FastdexApplication.java (系统找不到指定的路径。)

**Comment by typ0520** [comment]
@dongzy 你是使用了tinker的一键接入吗，估计是冲突了，它们也是替换了Appplication，需要让tinkerSupport先替换

**Comment by dongzy** [comment]
@typ0520 是啊，那怎么弄？不能用tinker的这个接入方式吗？

**Comment by typ0520** [comment]
@dongzy 我闲下来的时候尝试做下兼容吧，这周在忙公司的事情，tinkersupport的gradle插件代码没有开源出来，要花点时间研究下；还是建议你使用tinker原生的接入方式

**Comment by typ0520** [comment]
@dongzy 试下0.0.3-beta3这个版本，兼容了tinkerSupport的插件

**Comment by dongzy** [comment]
@typ0520 还是那个错误，我使用的是bugly提供的tinker，下面是我的配置。是使用了代理模式，也就是快速接入。
tinkerSupport {

    // 开启tinker-support插件，默认值true
    enable = true

    // 指定归档目录，默认值当前module的子目录tinker
    autoBackupApkDir = "${bakPath}"

    // 是否启用覆盖tinkerPatch配置功能，默认值false
    // 开启后tinkerPatch配置不生效，即无需添加tinkerPatch
    overrideTinkerPatchConfiguration = true

    // 编译补丁包时，必需指定基线版本的apk，默认值为空
    // 如果为空，则表示不是进行补丁包的编译
    // @{link tinkerPatch.oldApk }
//    baseApk =  "${bakPath}/${baseApkDir}/kp_v${android.defaultConfig.versionName}__91.apk"

    // 对应tinker插件applyMapping
//    baseApkProguardMapping = "${bakPath}/kp_v${android.defaultConfig.versionName}__91-mapping.txt"

    // 对应tinker插件applyResourceMapping
//    baseApkResourceMapping = "${bakPath}/${baseApkDir}/kp_v${android.defaultConfig.versionName}__91-R.txt"

    //这里强调一下，基线版本配置一个唯一的tinkerId，而这个基线版本能够应用补丁的前提是集成过热更新SDK，并启动上报过联网，
    // 这样我们后台会将这个tinkerId对应到一个目标版本，
    // 例如tinkerId = "bugly_1.0.0" 对应了一个目标版本是1.0.0，基于这个版本打的补丁包就能匹配到目标版本。
    tinkerId = "6.0.0"

    buildAllFlavorsDir = "${bakPath}/${baseApkDir}"

    enableProxyApplication = true

}

**Comment by typ0520** [comment]
@dongzy 加下我的qq  752554930

**Comment by xiang473535976** [comment]
Unable to instantiate application com.dx168.fastdex.runtime.FastdexApplication: java.lang.ClassNotFoundException

**Comment by xiang473535976** [comment]
没加热修复 这些…………

**Comment by typ0520** [comment]
@xiang473535976 你是不是开了instant run，如果不是有可能你加的一些插件也有替换application的逻辑，在fastdex执行以后又替换掉了；你能把完整的gradle build日志和运行期的错误堆栈贴出来吗

**Comment by typ0520** [comment]
@xiang473535976 找到原因了，你的android gradle build版本是2.3.0吧，最新的需要做下兼容，你可以先用2.2.0，等处理好了告诉你

**Comment by typ0520** [comment]
@xiang473535976 @dongzy 问题已解决0.0.3-beta7， android-gradle-build 2.3.0 获取dex输出目录的api变掉了，已经做了兼容处理
