### ISSUE TITLE
增量编译报FileNorFound的错误

### ISSUE THREAD

**Issue by sunshinehu** [typ0520/fastdex#83]
报FileNotFoundException 找不到 build\fastdex\Debug\patch\classes.dex 文件，请问是不是环境有问题

**Comment by typ0520** [comment]
clean一下在跑

发自我的 iPhone

**Comment by sunshinehu** [comment]
当然不是我的环境，我们工程在我的电脑上可以跑，在同事那边就会报这个错误，clean了之后第一次是好的，接下来的增量就又会报这个错误，请问有可能是哪些配置的问题。感谢这么快给予解答！

**Comment by typ0520** [comment]
可以提供一份完整的打包日志吗出错的时候

**Comment by sunshinehu** [comment]
貌似日志就这么点，我再重新导入试试，3q
