### ISSUE TITLE
补丁打包成功后安装时INSTALL_PARSE_FAILED_MANIFEST_MALFORMED

### ISSUE THREAD

**Issue by xiongtj** [typ0520/fastdex#89]
操作系统: windows
android gradle-build: 3.0.1
gradle:4.1

补丁打包时如果修改了manifest，打包成功后安装时出现:
Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED]

**Comment by typ0520** [comment]
@xiongtingjin 你检查下是不是这个问题

https://stackoverflow.com/questions/12396351/how-to-fix-install-parse-failed-manifest-malformed-in-my-android-application
http://blog.csdn.net/aibieqing241/article/details/12435693
