### ISSUE TITLE
AntilazyLoad的路径有问题

### ISSUE THREAD

**Issue by xiongtj** [typ0520/fastdex#91]
代码中如下，多了一个antilazyload包名
mv.visitFieldInsn(GETSTATIC, "fastdex/runtime/antilazyload/AntilazyLoad", "str", "Ljava/lang/String;")

**Comment by typ0520** [comment]
上次移动目录时这个忘记改了，刚已经改了这个问题最新版本0.8.8，谢谢你的反馈
